kind: pipeline
name: default

steps:
  # TODO::build
  - name: compile
    image: node
    commands:
      - npm install
      - ./node_modules/typescript/bin/tsc

  - name: npm
    image: plugins/npm
    settings:
      username: eignhpants
      password:
        from_secret: npm_pw
